use std::error::Error;
use std::fs;

fn main() -> Result<(), Box<dyn Error>> {

    Ok(())
}

#[cfg(test)]
mod tests {

    #[test]
    fn test() {
    }
}
